version: '3.6'
services:
  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - 3307:3306
    volumes:
      - ./data:/data
      - ./my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql      
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: budget68
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: [
              'mysqld', 
              '--character-set-server=utf8mb4', 
              '--collation-server=utf8mb4_unicode_ci',
              '--default-time-zone=Asia/Bangkok',
            ]

volumes:
  mysql_data: